// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5d228960-166a-4524-9755-37488471c0fd",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "80d99aa3-31b7-4b37-bede-37a3e3821ae6",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("api.Models.Portfolio", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("AppUserId", "StockId");

                    b.HasIndex("StockId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("api.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "McCullough, Reichert and Hauck",
                            Industry = "Grocery",
                            LastDiv = 4.94m,
                            MarketCap = 47648231724L,
                            Purchase = 179.04m,
                            Symbol = "ZWOSN"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Sipes and Sons",
                            Industry = "Automotive",
                            LastDiv = 6.87m,
                            MarketCap = 56941654642L,
                            Purchase = 142.74m,
                            Symbol = "VGBFD"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Spencer LLC",
                            Industry = "Kids",
                            LastDiv = 4.05m,
                            MarketCap = 23782501699L,
                            Purchase = 254.38m,
                            Symbol = "OQTFQ"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Hyatt LLC",
                            Industry = "Sports",
                            LastDiv = 6.75m,
                            MarketCap = 10085289771L,
                            Purchase = 376.01m,
                            Symbol = "AKY"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Hane, Hansen and Thompson",
                            Industry = "Grocery",
                            LastDiv = 7.21m,
                            MarketCap = 51582447334L,
                            Purchase = 202.07m,
                            Symbol = "ZQHV"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Hickle and Sons",
                            Industry = "Jewelery",
                            LastDiv = 9.48m,
                            MarketCap = 60687124289L,
                            Purchase = 256.33m,
                            Symbol = "HWH"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Ebert - Schulist",
                            Industry = "Jewelery",
                            LastDiv = 0.58m,
                            MarketCap = 60268912359L,
                            Purchase = 25.33m,
                            Symbol = "YNX"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Green, Yundt and Goyette",
                            Industry = "Jewelery",
                            LastDiv = 4.19m,
                            MarketCap = 49715225624L,
                            Purchase = 400.67m,
                            Symbol = "KSQK"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Hintz, Howe and Cummings",
                            Industry = "Games",
                            LastDiv = 3.35m,
                            MarketCap = 26248589239L,
                            Purchase = 366.01m,
                            Symbol = "USG"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Bins LLC",
                            Industry = "Automotive",
                            LastDiv = 9.34m,
                            MarketCap = 17825421757L,
                            Purchase = 63.25m,
                            Symbol = "KBED"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Cremin - Daugherty",
                            Industry = "Garden",
                            LastDiv = 9.20m,
                            MarketCap = 99802114187L,
                            Purchase = 72.50m,
                            Symbol = "BQR"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Tillman - Feeney",
                            Industry = "Tools",
                            LastDiv = 9.26m,
                            MarketCap = 65056930203L,
                            Purchase = 234.90m,
                            Symbol = "BKO"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "Collins, Bogan and Welch",
                            Industry = "Outdoors",
                            LastDiv = 7.67m,
                            MarketCap = 79110745488L,
                            Purchase = 81.76m,
                            Symbol = "FJGF"
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Lemke, Heidenreich and Gulgowski",
                            Industry = "Electronics",
                            LastDiv = 8.11m,
                            MarketCap = 61849397626L,
                            Purchase = 21.22m,
                            Symbol = "BCLT"
                        },
                        new
                        {
                            Id = 15,
                            CompanyName = "Grimes - Macejkovic",
                            Industry = "Books",
                            LastDiv = 3.28m,
                            MarketCap = 9904248549L,
                            Purchase = 431.78m,
                            Symbol = "ULMT"
                        },
                        new
                        {
                            Id = 16,
                            CompanyName = "Kilback - Quitzon",
                            Industry = "Movies",
                            LastDiv = 0.61m,
                            MarketCap = 17463370649L,
                            Purchase = 230.55m,
                            Symbol = "JDSW"
                        },
                        new
                        {
                            Id = 17,
                            CompanyName = "Cronin, Harber and Botsford",
                            Industry = "Outdoors",
                            LastDiv = 8.05m,
                            MarketCap = 1985795096L,
                            Purchase = 59.05m,
                            Symbol = "WAI"
                        },
                        new
                        {
                            Id = 18,
                            CompanyName = "Schuster - Jaskolski",
                            Industry = "Jewelery",
                            LastDiv = 8.79m,
                            MarketCap = 89196772410L,
                            Purchase = 356.10m,
                            Symbol = "BFTT"
                        },
                        new
                        {
                            Id = 19,
                            CompanyName = "Wiza - Swift",
                            Industry = "Movies",
                            LastDiv = 6.07m,
                            MarketCap = 38150114232L,
                            Purchase = 157.11m,
                            Symbol = "WVIUD"
                        },
                        new
                        {
                            Id = 20,
                            CompanyName = "Feeney and Sons",
                            Industry = "Kids",
                            LastDiv = 0.30m,
                            MarketCap = 53974896565L,
                            Purchase = 457.14m,
                            Symbol = "WGNVQ"
                        },
                        new
                        {
                            Id = 21,
                            CompanyName = "Grimes - Marvin",
                            Industry = "Industrial",
                            LastDiv = 6.19m,
                            MarketCap = 30887453871L,
                            Purchase = 62.98m,
                            Symbol = "NZEMK"
                        },
                        new
                        {
                            Id = 22,
                            CompanyName = "Heaney, Haag and Volkman",
                            Industry = "Beauty",
                            LastDiv = 4.96m,
                            MarketCap = 21447762508L,
                            Purchase = 340.45m,
                            Symbol = "WIT"
                        },
                        new
                        {
                            Id = 23,
                            CompanyName = "Marvin - Connelly",
                            Industry = "Industrial",
                            LastDiv = 8.71m,
                            MarketCap = 44696097359L,
                            Purchase = 114.30m,
                            Symbol = "WYD"
                        },
                        new
                        {
                            Id = 24,
                            CompanyName = "Feeney LLC",
                            Industry = "Books",
                            LastDiv = 2.01m,
                            MarketCap = 60181658681L,
                            Purchase = 419.06m,
                            Symbol = "QBVJ"
                        },
                        new
                        {
                            Id = 25,
                            CompanyName = "Ferry - Bailey",
                            Industry = "Health",
                            LastDiv = 1.95m,
                            MarketCap = 53242802307L,
                            Purchase = 123.42m,
                            Symbol = "OLVEC"
                        },
                        new
                        {
                            Id = 26,
                            CompanyName = "Berge and Sons",
                            Industry = "Movies",
                            LastDiv = 0.18m,
                            MarketCap = 12291305795L,
                            Purchase = 276.92m,
                            Symbol = "SMVLL"
                        },
                        new
                        {
                            Id = 27,
                            CompanyName = "Bayer, Gerhold and Upton",
                            Industry = "Movies",
                            LastDiv = 9.52m,
                            MarketCap = 96557373029L,
                            Purchase = 265.30m,
                            Symbol = "VDZ"
                        },
                        new
                        {
                            Id = 28,
                            CompanyName = "Waelchi, Welch and Lueilwitz",
                            Industry = "Grocery",
                            LastDiv = 1.01m,
                            MarketCap = 93932311589L,
                            Purchase = 133.44m,
                            Symbol = "UYPCY"
                        },
                        new
                        {
                            Id = 29,
                            CompanyName = "Stroman and Sons",
                            Industry = "Movies",
                            LastDiv = 1.67m,
                            MarketCap = 6130844979L,
                            Purchase = 401.29m,
                            Symbol = "DBX"
                        },
                        new
                        {
                            Id = 30,
                            CompanyName = "Hamill, Schmidt and Bartoletti",
                            Industry = "Jewelery",
                            LastDiv = 8.83m,
                            MarketCap = 14519939330L,
                            Purchase = 361.67m,
                            Symbol = "YTSV"
                        },
                        new
                        {
                            Id = 31,
                            CompanyName = "Mueller Group",
                            Industry = "Shoes",
                            LastDiv = 9.95m,
                            MarketCap = 44238708886L,
                            Purchase = 32.08m,
                            Symbol = "GOVX"
                        },
                        new
                        {
                            Id = 32,
                            CompanyName = "DuBuque - Herzog",
                            Industry = "Kids",
                            LastDiv = 5.91m,
                            MarketCap = 51846944180L,
                            Purchase = 362.80m,
                            Symbol = "CQAEJ"
                        },
                        new
                        {
                            Id = 33,
                            CompanyName = "Medhurst - Sawayn",
                            Industry = "Home",
                            LastDiv = 2.81m,
                            MarketCap = 78947063900L,
                            Purchase = 480.09m,
                            Symbol = "IKJ"
                        },
                        new
                        {
                            Id = 34,
                            CompanyName = "Bashirian, Hartmann and Pfeffer",
                            Industry = "Kids",
                            LastDiv = 2.13m,
                            MarketCap = 11655879818L,
                            Purchase = 228.00m,
                            Symbol = "OAKHS"
                        },
                        new
                        {
                            Id = 35,
                            CompanyName = "Treutel Group",
                            Industry = "Jewelery",
                            LastDiv = 3.96m,
                            MarketCap = 13301172369L,
                            Purchase = 43.18m,
                            Symbol = "AIM"
                        },
                        new
                        {
                            Id = 36,
                            CompanyName = "Kuhn - Feeney",
                            Industry = "Electronics",
                            LastDiv = 1.49m,
                            MarketCap = 78689320213L,
                            Purchase = 315.97m,
                            Symbol = "BHZG"
                        },
                        new
                        {
                            Id = 37,
                            CompanyName = "Rau - Koch",
                            Industry = "Movies",
                            LastDiv = 8.02m,
                            MarketCap = 96679204180L,
                            Purchase = 221.27m,
                            Symbol = "WSBD"
                        },
                        new
                        {
                            Id = 38,
                            CompanyName = "Sporer LLC",
                            Industry = "Shoes",
                            LastDiv = 5.64m,
                            MarketCap = 51979577807L,
                            Purchase = 17.44m,
                            Symbol = "FJFB"
                        },
                        new
                        {
                            Id = 39,
                            CompanyName = "Marks - Collier",
                            Industry = "Electronics",
                            LastDiv = 4.43m,
                            MarketCap = 79802240708L,
                            Purchase = 426.30m,
                            Symbol = "HVH"
                        },
                        new
                        {
                            Id = 40,
                            CompanyName = "Douglas - Walker",
                            Industry = "Sports",
                            LastDiv = 6.10m,
                            MarketCap = 34363633606L,
                            Purchase = 490.97m,
                            Symbol = "XDXRT"
                        },
                        new
                        {
                            Id = 41,
                            CompanyName = "Weber, Kiehn and Herzog",
                            Industry = "Tools",
                            LastDiv = 0.72m,
                            MarketCap = 89590417124L,
                            Purchase = 104.25m,
                            Symbol = "KSED"
                        },
                        new
                        {
                            Id = 42,
                            CompanyName = "Wisozk Inc",
                            Industry = "Books",
                            LastDiv = 5.84m,
                            MarketCap = 30874450122L,
                            Purchase = 447.65m,
                            Symbol = "VFTS"
                        },
                        new
                        {
                            Id = 43,
                            CompanyName = "Upton - Yundt",
                            Industry = "Clothing",
                            LastDiv = 6.74m,
                            MarketCap = 19153128980L,
                            Purchase = 270.99m,
                            Symbol = "SNI"
                        },
                        new
                        {
                            Id = 44,
                            CompanyName = "Williamson - Schaden",
                            Industry = "Kids",
                            LastDiv = 2.14m,
                            MarketCap = 56363832451L,
                            Purchase = 311.13m,
                            Symbol = "LUWZP"
                        },
                        new
                        {
                            Id = 45,
                            CompanyName = "Roob, Dooley and Weissnat",
                            Industry = "Kids",
                            LastDiv = 0.35m,
                            MarketCap = 64606523709L,
                            Purchase = 136.55m,
                            Symbol = "AQR"
                        },
                        new
                        {
                            Id = 46,
                            CompanyName = "Hauck, Jones and Labadie",
                            Industry = "Electronics",
                            LastDiv = 0.41m,
                            MarketCap = 45964087544L,
                            Purchase = 58.36m,
                            Symbol = "ZNGJ"
                        },
                        new
                        {
                            Id = 47,
                            CompanyName = "Brown - Willms",
                            Industry = "Baby",
                            LastDiv = 0.01m,
                            MarketCap = 74354434638L,
                            Purchase = 466.51m,
                            Symbol = "DUX"
                        },
                        new
                        {
                            Id = 48,
                            CompanyName = "Flatley, Skiles and Reilly",
                            Industry = "Home",
                            LastDiv = 8.80m,
                            MarketCap = 36528743888L,
                            Purchase = 98.66m,
                            Symbol = "JRRU"
                        },
                        new
                        {
                            Id = 49,
                            CompanyName = "Heidenreich - Welch",
                            Industry = "Sports",
                            LastDiv = 9.69m,
                            MarketCap = 11551101926L,
                            Purchase = 197.65m,
                            Symbol = "KYOWP"
                        },
                        new
                        {
                            Id = 50,
                            CompanyName = "Gutkowski - Leuschke",
                            Industry = "Movies",
                            LastDiv = 8.14m,
                            MarketCap = 21698133917L,
                            Purchase = 459.34m,
                            Symbol = "FTKJ"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.HasOne("api.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Stock", "Stock")
                        .WithMany("Comments")
                        .HasForeignKey("StockId");

                    b.Navigation("AppUser");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("api.Models.Portfolio", b =>
                {
                    b.HasOne("api.Models.AppUser", "AppUser")
                        .WithMany("Portfolios")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Stock", "Stock")
                        .WithMany("Portfolios")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("api.Models.Stock", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
